/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.Telas;

import br.senai.sc.Entidades.InfoPessoa;
import br.senai.sc.Entidades.Pontuacoes;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno_verbinnen
 */
public class TelaPontuacoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaPontuacoes
     */
    public TelaPontuacoes() {
        initComponents();
        setLocationRelativeTo(null);
        frase();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Blackout = new javax.swing.JLabel();
        pont3 = new javax.swing.JLabel();
        pont1 = new javax.swing.JLabel();
        pont2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        lfrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        met = new javax.swing.JLabel();
        ini = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        moedas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));

        Blackout.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        Blackout.setForeground(new java.awt.Color(255, 255, 255));
        Blackout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/blackout.png"))); // NOI18N

        pont3.setFont(new java.awt.Font("Rockwell Condensed", 1, 25)); // NOI18N
        pont3.setForeground(new java.awt.Color(255, 255, 255));
        pont3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pont3.setText("Pontuação");

        pont1.setFont(new java.awt.Font("Rockwell Condensed", 1, 25)); // NOI18N
        pont1.setForeground(new java.awt.Color(255, 255, 255));
        pont1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pont1.setText("Pontuação");

        pont2.setFont(new java.awt.Font("Rockwell Condensed", 1, 25)); // NOI18N
        pont2.setForeground(new java.awt.Color(255, 255, 255));
        pont2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pont2.setText("Pontuação");

        total.setFont(new java.awt.Font("Rockwell Condensed", 1, 25)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("Pontuação");

        lfrase.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        lfrase.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/suap.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        met.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        met.setForeground(new java.awt.Color(255, 255, 255));
        met.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        met.setText("Metros Percorridos:");

        ini.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        ini.setForeground(new java.awt.Color(255, 255, 255));
        ini.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ini.setText("Inimigos Mortos:");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Total:");

        moedas.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        moedas.setForeground(new java.awt.Color(255, 255, 255));
        moedas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        moedas.setText("Moedas Coletadas:");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(Blackout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(680, 680, 680)
                                .addComponent(pont1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ini, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(pont2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(moedas, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(pont3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(440, 440, 440)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(met, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lfrase, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Blackout, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lfrase, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pont1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(met, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ini, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pont2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moedas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pont3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Pontuacoes pont = new Pontuacoes();
       met.setText("Metros Percorridos: "+pont.getMetros());
       ini.setText("Inimigos Mortos: "+pont.getInimigos());
       moedas.setText("Moedas Coletadas: "+pont.getMoedas());
       pont1.setText(""+(pont.getMetros()*2));
       pont2.setText(""+(pont.getInimigos()*3));
       pont3.setText(""+(pont.getMoedas()*1));
       total.setText(""+((pont.getMetros()*2)+(pont.getInimigos()*3)+(pont.getMoedas()*1)));
       
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(InfoPessoa.getResolucao()==1){
            new TelaPrincipal().setVisible(true);
        }else if(InfoPessoa.getResolucao()==2){
            new TelaPrincipal2().setVisible(true);
        }else if(InfoPessoa.getResolucao()==3){
             new TelaPrincipal3().setVisible(true);
        }
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPontuacoes().setVisible(true);
            }
        });
    }
    
    public void frase(){
        String[] frase = new String[10];
        frase[0]="<html> Fala-se tanto da necessidade de deixar um planeta melhor para os nossos filhos e,<br> esquece-se da urgência de deixarmos filhos melhores para o nosso planeta.<br> Seja consciente! </html>";
        frase[1]="<html> O laço essencial que nos une é que todos habitamos este pequeno planeta. Todos respiramos o mesmo ar. Todos nos preocupamos com o futuro<br> dos nossos filhos. E todos somos mortais. Economize energia antes que<br> tenhamos que destruir a natureza que nos cerca! </html>";
        frase[2]="<html> Semear ideias ecológicas e plantar sustentabilidade é ter a garantia<br> de colhermos um futuro fértil e consciente. </html>";
        frase[3]="<html> Só consuma o que você precisa, a sustentabilidade de nosso planeta depende<br> de um consumo consciente e responsável. </html>";
        frase[4]="<html> Semeai a educação e a sustentabilidade pois essas são as estradas que levam<br> ao futuro perfeito e eterno. </html>";
        frase[5]="<html> Educação, saúde e sustentabilidade deveriam ser prioridade e paixão nacional,<br> não futebol. </html>";
        frase[6]="<html> A ignorância pela falta de informação é uma faca que fere a essência<br> da conscientização do homem. Estude, conscientize-se! </html>";
        frase[7]="<html> A sustentabilidade é a abertura para o futuro, caso fecharmos não existirá futuro. </html>";
        frase[8]="<html> Plantar ideias ecológicas é a garantia de um futuro fértil, tempo de<br> colhermos sustentabilidade. </html>";
        frase[9]="<html> Economizar energia não é apenas bom para o mundo, mas também é<br> bom para o bolso. </html>";
        
        Random gerador = new Random();
        int i = gerador.nextInt(10);
        lfrase.setText(frase[i]);
//        JOptionPane.showMessageDialog(null, frase[i]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Blackout;
    private javax.swing.JLabel ini;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lfrase;
    private javax.swing.JLabel met;
    private javax.swing.JLabel moedas;
    private javax.swing.JLabel pont1;
    private javax.swing.JLabel pont2;
    private javax.swing.JLabel pont3;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
