/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.Telas;

import br.senai.sc.DAO.PersonagensDAO;
import br.senai.sc.DAO.PersonagenspessoaDAO;
import br.senai.sc.DAO.PessoasDAO;
import br.senai.sc.Entidades.InfoPessoa;
import br.senai.sc.Entidades.Personagens;
import br.senai.sc.Entidades.Personagenspessoa;
import br.senai.sc.Entidades.Pessoas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author bruno_verbinnen
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    Pessoas pess = new Pessoas();
    PessoasDAO pessDAO = new PessoasDAO();
    Personagenspessoa pp = new Personagenspessoa();
    PersonagenspessoaDAO ppDAO = new PersonagenspessoaDAO();
    Personagens pers = new Personagens();
    PersonagensDAO persDAO = new PersonagensDAO();
    InfoPessoa InfoP = new InfoPessoa();
    int cod = InfoP.getId();
    String Nome = InfoP.getNome();
    Boolean Adm = InfoP.getAdm();
    JLabel moedas = new JLabel();
    JTable m10 = new JTable();
    List<JLabel> Nomes = new ArrayList<>();
    List<JLabel> Pontuacao = new ArrayList<>();
    int id;
    
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        bar.setBackground(Color.BLACK);
        bar.add(Box.createRigidArea(new Dimension(1450,0)));
        moedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/moeda.gif")));
        bar.add(moedas);
        imgpers();
    }
    public void inimoedas(){
        try {
//            pess.setIdPessoa(InfoP.getId());
            pess = pessDAO.getPessoaPorID(InfoP.getId());
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void imgpers(){
        pess.setIdPessoa(InfoP.getId());
        pp.setIdPessoa(pess);
        try {
            id = ppDAO.AcharPersonagem(pp);
        } catch (Exception ex) {
            Logger.getLogger(TelaEscolhaPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(id!=-1){
            try {
                    pers = persDAO.getPersonagemPorID(id);
                } catch (Exception ex) {
                    Logger.getLogger(TelaEscolhaPersonagem.class.getName()).log(Level.SEVERE, null, ex);
                }

            per.setIcon(new javax.swing.ImageIcon(getClass().getResource(pers.getGif())));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        per = new javax.swing.JLabel();
        ape = new javax.swing.JLabel();
        bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        painel.setBackground(new java.awt.Color(255, 255, 255));
        painel.setPreferredSize(new java.awt.Dimension(1366, 768));
        painel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                painelKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/suaMelhor_1.png"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });

        MP.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        MP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MP.setText("-----");
        MP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MPKeyPressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/TOP10_1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/p2 (1).png"))); // NOI18N

        per.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perMouseClicked(evt);
            }
        });

        ape.setFont(new java.awt.Font("Bell MT", 0, 30)); // NOI18N
        ape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ape.setText("Aperte no personagem ou S para iniciar o jogo");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(910, 910, 910)
                        .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelLayout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel2)))
                            .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(118, 118, 118)
                .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bar.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("<html> <font size='6' face='Baskerville Old Face'>Menu");

        jMenuItem1.setFont(new java.awt.Font("Bell MT", 1, 25)); // NOI18N
        jMenuItem1.setText("Ajuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Bell MT", 1, 25)); // NOI18N
        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        bar.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("<html> <font size='6' face='Baskerville Old Face'>Loja");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        bar.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("<html> <font size='6' face='Baskerville Old Face'>Escolha de Personagem");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        bar.add(jMenu3);

        setJMenuBar(bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        pp.setIdPessoa(pess);
        try {
            if(ppDAO.AcharPersonagem(pp)==-1){
                ape.setText("Pressione S para jogar");
            }else{
                ape.setText("Aperte no personagem ou S para iniciar o jogo");
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        setExtendedState(MAXIMIZED_BOTH);
        try {
            pess = pessDAO.getPessoaPorID(InfoP.getId());
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        moedas.setText("<html> <font size='6' face='Baskerville Old Face'  >"+pess.getMoedas()+"</font></html>");
        Pontuacoes();
        info();
    }//GEN-LAST:event_formWindowActivated

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_S){
            Jogar();
        }     
    }//GEN-LAST:event_formKeyPressed

    private void MPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MPKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_S){
            Jogar();
        }
    }//GEN-LAST:event_MPKeyPressed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_S){
            Jogar();
        }
    }//GEN-LAST:event_jLabel1KeyPressed

    private void painelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painelKeyPressed
        // TODO add your handling code here:
        Jogar();
    }//GEN-LAST:event_painelKeyPressed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        TelaLojaPersonagem abrir = new TelaLojaPersonagem();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        TelaEscolhaPersonagem abrir = new TelaEscolhaPersonagem();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void perMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perMouseClicked
        // TODO add your handling code here:
        Jogar();
    }//GEN-LAST:event_perMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:]
     new TelaAjuda().setVisible(true);
     dispose();
     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        InfoP.setId(0);
        InfoP.setNome("");
        InfoP.setResolucao(0);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    public void Jogar(){
     try {
            pp.setIdPessoa(pess);
            if(ppDAO.AcharPersonagem(pp)==-1){
                JOptionPane.showMessageDialog(null, "Compre ou selecione um personagem");
            }else{
                TelaJogo abrir = new TelaJogo();
                abrir.setVisible(true);
                dispose();
            }
            
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     
    }
    
    public void info(){
        InfoPessoa IP = new InfoPessoa();
        int cod = IP.getId();
        try {
            pess = pessDAO.getPessoaPorID(cod);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

//        Moedas.setText("R$" + pess.getMoedas());
    
     
    }
    
    public void Pontuacoes(){
        try {
            pess = pessDAO.getPessoaPorID(cod);     
//            pess = pessDAO.getPessoaPorID(1);
            MP.setText(""+pess.getPontuacao());
            m10.setModel(pessDAO.getMd10());
            criarlabelsdepontuacao();
            
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    public void criarlabelsdepontuacao(){
        int y = 200;
        for(int i=0; i<m10.getRowCount() ; i++){
//            JOptionPane.showMessageDialog(null, i);
//            System.out.println(i);
            JLabel novonome = new JLabel();
            novonome.setText("<html> <font size='25' face='Baskerville Old Face'>"+m10.getValueAt(i, 0)+"</font></html>");
            novonome.setRequestFocusEnabled(false);
            novonome.setBounds(1550, y, 200, 35);
            Nomes.add(novonome);
            for (JLabel NomeAtual : Nomes) {
                painel.add(NomeAtual);
            }
            
            JLabel novapontuacao = new JLabel();
            novapontuacao.setText("<html> <font size='25' face='Baskerville Old Face'>"+m10.getValueAt(i, 1)+"</font></html>");
            novapontuacao.setRequestFocusEnabled(false);
            novapontuacao.setBounds(1750, y, 100, 35);
            Pontuacao.add(novapontuacao);
            for (JLabel PontuacaoAtual : Pontuacao) {
                painel.add(PontuacaoAtual);
            }
            y+=50;
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MP;
    private javax.swing.JLabel ape;
    private javax.swing.JMenuBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel painel;
    private javax.swing.JLabel per;
    // End of variables declaration//GEN-END:variables
}
